version: '3.4'

services:
  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: password
      DB_DB: db
    ports:
      - 8000:8000
    networks:
      - default

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bsolano@estudiantec.cr
      PGADMIN_DEFAULT_PASSWORD: test 
    ports:
      - 5050:80
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: